apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.express.name }}
  labels:
    app: {{ .Values.express.name }}
spec:
  replicas: {{ .Values.express.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.express.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.express.name }}
    spec:
      containers:
      - name: {{ .Values.express.name }}
        image: {{ .Values.express.name }}
        ports:
        - containerPort: {{ .Values.express.port }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.app.name }}-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.express.name }}-configmap
              key: database_url
